// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtNu_Yc7IUJGFdrYCvuObqaw03-D7K8J4',
    appId: '1:505889048583:web:15faab7d02e567e63d82a2',
    messagingSenderId: '505889048583',
    projectId: 'flutter-application-1-6750a',
    authDomain: 'flutter-application-1-6750a.firebaseapp.com',
    storageBucket: 'flutter-application-1-6750a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBcZLbGXTrxHzs0HJVeHf5cP9DQiMOzi4',
    appId: '1:505889048583:android:4fc7d8cb893945153d82a2',
    messagingSenderId: '505889048583',
    projectId: 'flutter-application-1-6750a',
    storageBucket: 'flutter-application-1-6750a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ur-N1m41hhRD8e1G2cgE5W5a5V_70PM',
    appId: '1:505889048583:ios:77ed5c0f69d8caf53d82a2',
    messagingSenderId: '505889048583',
    projectId: 'flutter-application-1-6750a',
    storageBucket: 'flutter-application-1-6750a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5ur-N1m41hhRD8e1G2cgE5W5a5V_70PM',
    appId: '1:505889048583:ios:77ed5c0f69d8caf53d82a2',
    messagingSenderId: '505889048583',
    projectId: 'flutter-application-1-6750a',
    storageBucket: 'flutter-application-1-6750a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtNu_Yc7IUJGFdrYCvuObqaw03-D7K8J4',
    appId: '1:505889048583:web:87b89e3480e06e983d82a2',
    messagingSenderId: '505889048583',
    projectId: 'flutter-application-1-6750a',
    authDomain: 'flutter-application-1-6750a.firebaseapp.com',
    storageBucket: 'flutter-application-1-6750a.firebasestorage.app',
  );
}
